# Generated by Django 5.2 on 2025-08-13 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cultivo_deseado', models.CharField(blank=True, max_length=100, null=True)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
