# Generated by Django 5.2 on 2025-08-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudrecomendacion',
            old_name='municipio',
            new_name='cultivo_deseado',
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad en kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='clima_recomendacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='dias_cultivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='ingreso_proyectado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingreso total proyectado', max_digits=15),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='precio_estimado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio estimado por kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='viabilidad',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudrecomendacion',
            name='fecha_cultivo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
