# Generated by Django 5.2 on 2025-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudrecomendacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='fecha_cosecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='mes_cultivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='viabilidad',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
