# Generated by Django 5.2 on 2025-08-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_municipio_solicitudrecomendacion_cultivo_deseado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
