# Generated by Django 5.2 on 2025-08-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_solicitudrecomendacion_fecha_cosecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecomendacion',
            name='mes_cultivo',
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad en kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='clima_recomendacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='dias_cultivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='fecha_cultivo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
