# Generated by Django 5.2 on 2025-08-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_solicitudrecomendacion_mes_cultivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='ingreso_proyectado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingreso total proyectado', max_digits=15),
        ),
        migrations.AddField(
            model_name='solicitudrecomendacion',
            name='precio_estimado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio estimado por kg', max_digits=10),
        ),
    ]
