# Generated by Django 5.2 on 2025-08-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_solicitudrecomendacion_ingreso_proyectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
