# Generated by Django 5.2 on 2025-08-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_solicitudrecomendacion_ingreso_proyectado_and_more'),
    ]

    operations = [
    ]
