# Generated by Django 5.2 on 2025-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20250818_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudrecomendacion',
            old_name='cultivo_deseado',
            new_name='municipio',
        ),
        migrations.RemoveField(
            model_name='solicitudrecomendacion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solicitudrecomendacion',
            name='clima_recomendacion',
        ),
        migrations.RemoveField(
            model_name='solicitudrecomendacion',
            name='dias_cultivo',
        ),
        migrations.RemoveField(
            model_name='solicitudrecomendacion',
            name='ingreso_proyectado',
        ),
        migrations.RemoveField(
            model_name='solicitudrecomendacion',
            name='precio_estimado',
        ),
        migrations.RemoveField(
            model_name='solicitudrecomendacion',
            name='viabilidad',
        ),
        migrations.AlterField(
            model_name='solicitudrecomendacion',
            name='fecha_cultivo',
            field=models.DateField(help_text='Fecha de siembra'),
        ),
    ]
