# Generated by Django 5.2.5 on 2025-08-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_reset_token_usuario_reset_token_expires'),
        ('usuarios', '0007_rename_cultivo_deseado_solicitudrecomendacion_municipio_and_more'),
    ]

    operations = [
    ]
